title: GVL
description: GVL Information Security Consultancy

url: http://gijsvl.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: About
    url: /index.html
  - title: Services
    url: /index.html#services
  - title: Contact
    url: /index.html#contact
  - title: Research
    url: /research
  - title: Blog
    url: /blog

social:
  github: gijsvl
  twitter: gijsvanlaer
  linkedin: gijs-van-laer-b3325637
  email: contact@gijsvanlaer.be
